server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: update
indexing-settings:
  sites:
#   - url: https://playback.ru
#     name: PlayBack.Ru
#   - url: https://skillbox.ru
#     name: Skillbox
   - url: https://ipfran.ru
     name: ИПФ РАН
  agent: TheSkillBoxFinalHomeWorkSearchBot
logging:
  level:
    root: info